# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # https://github.com/travis-ci/travis-ci/issues/8589
  - curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.7/bin/python
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python"
  - dephell deps install --env=$ENV
  - pip install coveralls
script:
  - dephell venv run --env=tests coverage run --source deal tests.py
  - coveralls

matrix:
  include:
    - python: "3.7"
      script:
        - dephell venv run --env=flake8
