# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial

# do not run Travis for PR's twice (as for push and as for PR)
branches:
  only:
    - master

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # https://github.com/travis-ci/travis-ci/issues/8589
  - curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.7/bin/python
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python"
  - dephell deps install --env=$ENV
  - pip install coveralls
script:
  - dephell venv run --env=$ENV
  - coveralls

# run tests
env: ENV=tests
python:
  - "3.6.7"
  - "3.7"
  - "3.8-dev"

# run flake8
matrix:
  include:
    - python: "3.7"
      env: ENV=flake8
      script:
        - dephell venv run --env=$ENV
