[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.dephell.main]
from = {format = "flit", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
tag = "v."


[tool.isort]
line_length = 90
combine_as_imports = true
balanced_wrapping = true
lines_after_imports = 2
skip = "venvs/"
not_skip = "__init__.py"
multi_line_output = 5
include_trailing_comma = true

import_heading_stdlib = "built-in"
import_heading_thirdparty = "external"
import_heading_firstparty = "project"
import_heading_localfolder = "app"


[tool.flit.metadata]
module = "deal"
license = "MIT"
author = "Gram"
author-email = "gram@orsinium.dev"
home-page = "https://github.com/orsinium/deal"
description-file = "README.md"
requires-python = ">=3.6"
keywords = "deal,contracts,pre,post,invariant,decorators,validation,pythonic,functional"

classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]

requires = [
    "astroid",
    "hypothesis",
    "pygments",
    "typeguard",
    "vaa>=0.2.1",
    "z3-solver",
]

[tool.flit.metadata.requires-extra]
tests = [
    "coverage",
    "pytest-cov",
    "isort",
    "marshmallow",
    "mypy",
    "pytest",
    "urllib3",
]
docs = [
    "m2r",
    "recommonmark",
    "sphinx",
    "sphinx-rtd-theme",
]

[tool.flit.entrypoints."flake8.extension"]
DEAL = "deal.linter:Checker"

[tool.pytest.ini_options]
addopts = [
    "--cov=deal",
    "--cov-report=html",
    "--cov-report=term-missing:skip-covered",
    "--cov-fail-under=100",
]

[tool.coverage.run]
branch = true
omit = [
    "deal/linter/_template.py",
    "deal/__main__.py",
    "deal/linter/__main__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "pass",
]
