[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.dephell.flake8]
from = {format = "pip", path = "requirements-flake.txt"}
python = ">=3.6"
command = "flake8"

[tool.dephell.tests]
from = {format = "poetry", path = "pyproject.toml"}
envs = ["main", "dev"]
tests = ["tests.py"]
command = "python tests.py"


[tool.isort]
line_length = 120
combine_as_imports = true
balanced_wrapping = true
lines_after_imports = 2
not_skip = "__init__.py"
multi_line_output = 5

import_heading_stdlib = "built-in"
import_heading_thirdparty = "external"
import_heading_firstparty = "project"
import_heading_localfolder = "app"


[tool.poetry]
name = "deal"
version = "2.2.1"
description = "Programming by contract"
license = "MIT"
authors = ["Gram <master_fess@mail.ru>"]
repository = "https://github.com/orsinium/deal"
readme = "README.md"
keywords = [
    "deal", "contracts", "pre", "post", "invariant", "decorators",
    "validation", "pythonic", "functional",
]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]

[tool.poetry.dependencies]
python = ">=3.5"

[tool.poetry.dev-dependencies]
coverage = "*"
djburger = "*"
marshmallow = "*"
urllib3 = "*"
